// Generated by scripts/export-new-eden-systems.py. Do not edit by hand.
#pragma once

#include <cstdint>

namespace neweden
{
constexpr uint32_t kExpectedEdgeCount = 6989;
constexpr uint32_t kExpectedDirectedStargateCount = 13978;
constexpr uint32_t kExpectedJitaAmarrHops = 11;
constexpr uint32_t kExpectedJitaReachable = 5228;
constexpr uint32_t kJitaId = 30000142;
constexpr uint32_t kAmarrId = 30002187;
constexpr uint32_t kNiarjaId = 30003504;

struct NeighborExpect
{
	uint32_t id;
	const char* name;
};

constexpr NeighborExpect kJitaNeighbors[] = {
	{ 30000138, "Ikuchi" },
	{ 30000140, "Maurasi" },
	{ 30000143, "Niyabainen" },
	{ 30000144, "Perimeter" },
	{ 30000145, "New Caldari" },
	{ 30001363, "Sobaseki" },
	{ 30002780, "Muvolailen" },
};

constexpr NeighborExpect kAmarrNeighbors[] = {
	{ 30002189, "Hedion" },
	{ 30002192, "Irnin" },
	{ 30002282, "Bhizheba" },
	{ 30003491, "Ashab" },
	{ 30003522, "Sarum Prime" },
	{ 30005038, "Kor-Azor Prime" },
};

constexpr NeighborExpect kDodixieNeighbors[] = {
	{ 30002655, "Vylade" },
	{ 30002656, "Auvergne" },
	{ 30002658, "Agrallarier" },
	{ 30002661, "Botane" },
	{ 30003031, "Athinard" },
	{ 30003032, "Meves" },
};

constexpr NeighborExpect kRensNeighbors[] = {
	{ 30002507, "Abudban" },
	{ 30002509, "Odatrik" },
	{ 30002526, "Frarn" },
};

constexpr NeighborExpect kHekNeighbors[] = {
	{ 30002049, "Uttindar" },
	{ 30002054, "Hror" },
	{ 30002068, "Nakugard" },
	{ 30002543, "Eystur" },
	{ 30002723, "Otou" },
};

constexpr NeighborExpect kZarzakhNeighbors[] = {
	{ 30001041, "G-0Q86" },
	{ 30001269, "H-PA29" },
	{ 30002086, "Turnur" },
	{ 30003841, "Alsavoinon" },
};

}
