// Generated by scripts/export-new-eden-systems.py. Do not edit by hand.
#pragma once

#include <cstdint>

namespace neweden
{
constexpr uint32_t kExpectedSystemCount = 5485;
constexpr uint32_t kExpectedKnownSpaceCount = 5485;
constexpr uint32_t kExpectedOtherSpaceCount = 0;
constexpr uint32_t kExpectedSdeBuild = 3464040;
constexpr float kCentreX = -9.10258865f;
constexpr float kCentreY = -3.99724412f;
constexpr float kCentreZ = 0.612724304f;

struct AnchorExpect
{
	uint32_t id;
	const char* name;
	float x;
	float y;
	float z;
};

constexpr AnchorExpect kAnchors[] = {
	{ 30000142, "Jita", -13.6432199f, -6.42233706f, -12.4174662f },
	{ 30002187, "Amarr", -21.6436272f, -4.25352859f, 6.09104443f },
	{ 30002659, "Dodixie", -19.8326607f, -5.62804365f, -2.92733073f },
	{ 30002510, "Rens", -10.4780483f, -4.26375294f, 0.303142577f },
	{ 30002053, "Hek", -13.7312202f, -4.57660341f, -5.91644526f },
};
}
